/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    drops: Drop;
    artworks: Artwork;
    artists: Artist;
    causes: Cause;
    'impact-stats': ImpactStat;
    'impact-entries': ImpactEntry;
    journal: Journal;
    testimonials: Testimonial;
    faqs: Faq;
    'homepage-sections': HomepageSection;
    newsletter: Newsletter;
    carts: Cart;
    orders: Order;
    coupons: Coupon;
    'shipping-methods': ShippingMethod;
    transactions: Transaction;
    'inventory-movements': InventoryMovement;
    'contact-submissions': ContactSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    drops: DropsSelect<false> | DropsSelect<true>;
    artworks: ArtworksSelect<false> | ArtworksSelect<true>;
    artists: ArtistsSelect<false> | ArtistsSelect<true>;
    causes: CausesSelect<false> | CausesSelect<true>;
    'impact-stats': ImpactStatsSelect<false> | ImpactStatsSelect<true>;
    'impact-entries': ImpactEntriesSelect<false> | ImpactEntriesSelect<true>;
    journal: JournalSelect<false> | JournalSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'homepage-sections': HomepageSectionsSelect<false> | HomepageSectionsSelect<true>;
    newsletter: NewsletterSelect<false> | NewsletterSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    'shipping-methods': ShippingMethodsSelect<false> | ShippingMethodsSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'inventory-movements': InventoryMovementsSelect<false> | InventoryMovementsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    about: About;
    contact: Contact;
  };
  globalsSelect: {
    about: AboutSelect<false> | AboutSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor' | 'customer';
  name?: string | null;
  /**
   * Products saved by this account. Storefront APIs only expose the signed-in user's list.
   */
  wishlist?: (number | Product)[] | null;
  /**
   * Shipping and billing addresses saved by this account.
   */
  addresses?:
    | {
        label: string;
        isDefault?: boolean | null;
        name: string;
        company?: string | null;
        line1: string;
        line2?: string | null;
        city: string;
        state?: string | null;
        postalCode?: string | null;
        /**
         * ISO 3166-1 alpha-2 country code.
         */
        country: string;
        phone: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Lowercase letters, numbers, and hyphens only.
   */
  slug: string;
  name: string;
  form: string;
  /**
   * Display price, e.g. $120 or From $95.
   */
  price: string;
  currency?: ('USD' | 'LBP' | 'EUR' | 'GBP') | null;
  /**
   * Calculated from variants and used by Shop filters and sorting.
   */
  minPrice?: number | null;
  /**
   * Calculated from variants and used by Shop filters.
   */
  maxPrice?: number | null;
  edition: string;
  image?: (number | null) | Media;
  /**
   * Optional fallback for migrated fixture images. Prefer local media uploads for production content.
   */
  externalImageUrl?: string | null;
  imageAlt: string;
  /**
   * Optional detail and lifestyle images for the product page. The main image is shown first.
   */
  gallery?:
    | {
        image?: (number | null) | Media;
        externalImageUrl?: string | null;
        alt: string;
        id?: string | null;
      }[]
    | null;
  story: string;
  /**
   * Object dimensions or garment measurements shown on the product page.
   */
  dimensions?: string | null;
  careInstructions?: string | null;
  shippingReturns?: string | null;
  /**
   * Optional link to the batch this product belongs to.
   */
  drop?: (number | null) | Drop;
  artist?: (number | null) | Artist;
  artwork?: (number | null) | Artwork;
  cause?: (number | null) | Cause;
  materials: {
    label: string;
    id?: string | null;
  }[];
  /**
   * Use variants for size, color, object type, or limited edition options.
   */
  variants: {
    name: string;
    /**
     * Unique stock keeping unit used by fulfillment.
     */
    sku: string;
    price: number;
    compareAtPrice?: number | null;
    color?:
      | (
          | 'black'
          | 'white'
          | 'off-white'
          | 'cream'
          | 'beige'
          | 'tan'
          | 'brown'
          | 'grey'
          | 'green'
          | 'blue'
          | 'purple'
          | 'pink'
          | 'red'
          | 'orange'
          | 'yellow'
          | 'metallic'
          | 'multicolor'
        )
      | null;
    size?: ('one-size' | 'xxs' | 'xs' | 's' | 'm' | 'l' | 'xl' | 'xxl' | 'xxxl') | null;
    inventory: number;
    reserved: number;
    lowStockThreshold?: number | null;
    attributes?:
      | {
          name: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    isAvailable?: boolean | null;
    id?: string | null;
  }[];
  /**
   * Calculated from variants and used by Shop filters.
   */
  colors?:
    | (
        | 'black'
        | 'white'
        | 'off-white'
        | 'cream'
        | 'beige'
        | 'tan'
        | 'brown'
        | 'grey'
        | 'green'
        | 'blue'
        | 'purple'
        | 'pink'
        | 'red'
        | 'orange'
        | 'yellow'
        | 'metallic'
        | 'multicolor'
      )[]
    | null;
  /**
   * Calculated from variants and used by Shop filters.
   */
  sizes?: ('one-size' | 'xxs' | 'xs' | 's' | 'm' | 'l' | 'xl' | 'xxl' | 'xxxl')[] | null;
  /**
   * Calculated from sellable variant inventory.
   */
  availability: 'in-stock' | 'low-stock' | 'out-of-stock';
  /**
   * Optional synonyms or terms shoppers may use. Do not repeat the product name.
   */
  searchKeywords?: string | null;
  /**
   * Admin-facing rollup for quick filtering until inventory sync is automated.
   */
  totalInventory?: number | null;
  shippingProfile?: ('standard' | 'fragile' | 'textile' | 'digital') | null;
  /**
   * Optional complementary products shown in the cart. Unavailable products are filtered at request time.
   */
  upsells?: (number | Product)[] | null;
  /**
   * Promote this entry in curated modules.
   */
  isFeatured?: boolean | null;
  seo?: {
    /**
     * Optional override for browser and search result titles.
     */
    metaTitle?: string | null;
    /**
     * Optional search description. Keep it concise.
     */
    metaDescription?: string | null;
    openGraphImage?: (number | null) | Media;
  };
  isPublished?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  /**
   * Photographer, artist, or rights holder credit.
   */
  credit?: string | null;
  usage?: ('editorial' | 'product' | 'artwork' | 'portrait' | 'process-video' | 'impact' | 'social') | null;
  /**
   * Optional image focal point for responsive crops.
   */
  focalPoint?: {
    x?: number | null;
    y?: number | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "drops".
 */
export interface Drop {
  id: number;
  /**
   * Lowercase letters, numbers, and hyphens only.
   */
  slug: string;
  eyebrow: string;
  title: string;
  summary: string;
  batchSize: number;
  reserved: number;
  status: 'draft' | 'preview' | 'live' | 'sold-out' | 'closed';
  opensAt?: string | null;
  closesAt: string;
  products?: (number | Product)[] | null;
  artist: number | Artist;
  artwork: number | Artwork;
  cause: number | Cause;
  /**
   * The percentage of this batch's proceeds allocated directly to the NGO partner.
   */
  donationPercentage?: number | null;
  image?: (number | null) | Media;
  /**
   * Optional fallback for migrated fixture images. Prefer local media uploads for production content.
   */
  externalImageUrl?: string | null;
  imageAlt: string;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  milestones: {
    label: string;
    value: string;
    progress: number;
    id?: string | null;
  }[];
  /**
   * Explain how proceeds from this batch are divided.
   */
  allocation?:
    | {
        label: string;
        percentage: number;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    href?: string | null;
    style?: ('primary' | 'secondary' | 'text') | null;
  };
  seo?: {
    /**
     * Optional override for browser and search result titles.
     */
    metaTitle?: string | null;
    /**
     * Optional search description. Keep it concise.
     */
    metaDescription?: string | null;
    openGraphImage?: (number | null) | Media;
  };
  /**
   * The homepage reads the first published record marked current.
   */
  isCurrent?: boolean | null;
  isPublished?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artists".
 */
export interface Artist {
  id: number;
  /**
   * Lowercase letters, numbers, and hyphens only.
   */
  slug: string;
  name: string;
  role: string;
  quote: string;
  bio: string;
  location?: string | null;
  website?: string | null;
  /**
   * Handle or profile URL.
   */
  instagram?: string | null;
  image?: (number | null) | Media;
  /**
   * Optional fallback for migrated fixture images. Prefer local media uploads for production content.
   */
  externalImageUrl?: string | null;
  imageAlt: string;
  /**
   * A short, silent studio or making-of film. Upload MP4/WebM to local media.
   */
  processVideo?: (number | null) | Media;
  /**
   * Optional hosted-video fallback. A local process video takes precedence.
   */
  processVideoUrl?: string | null;
  processVideoPoster?: (number | null) | Media;
  processVideoCaption?: string | null;
  portraitGallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  facts: {
    label: string;
    value: string;
    id?: string | null;
  }[];
  representativeWorks?:
    | {
        title: string;
        year?: string | null;
        medium?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Promote this entry in curated modules.
   */
  isFeatured?: boolean | null;
  seo?: {
    /**
     * Optional override for browser and search result titles.
     */
    metaTitle?: string | null;
    /**
     * Optional search description. Keep it concise.
     */
    metaDescription?: string | null;
    openGraphImage?: (number | null) | Media;
  };
  /**
   * The homepage reads the first published record marked current.
   */
  isCurrent?: boolean | null;
  isPublished?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artworks".
 */
export interface Artwork {
  id: number;
  /**
   * Lowercase letters, numbers, and hyphens only.
   */
  slug: string;
  title: string;
  artistLine: string;
  summary: string;
  image?: (number | null) | Media;
  /**
   * Optional fallback for migrated fixture images. Prefer local media uploads for production content.
   */
  externalImageUrl?: string | null;
  imageAlt: string;
  details: {
    label: string;
    title: string;
    body: string;
    x: number;
    y: number;
    id?: string | null;
  }[];
  /**
   * The homepage reads the first published record marked current.
   */
  isCurrent?: boolean | null;
  isPublished?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "causes".
 */
export interface Cause {
  id: number;
  /**
   * Lowercase letters, numbers, and hyphens only.
   */
  slug: string;
  name: string;
  focus: string;
  legalName?: string | null;
  registrationNumber?: string | null;
  website?: string | null;
  summary: string;
  contact?: {
    name?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  image?: (number | null) | Media;
  /**
   * Optional fallback for migrated fixture images. Prefer local media uploads for production content.
   */
  externalImageUrl?: string | null;
  imageAlt: string;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  metrics: {
    label: string;
    value: string;
    progress: number;
    id?: string | null;
  }[];
  programs?:
    | {
        name: string;
        description: string;
        /**
         * Example: $18 per object or 25% of proceeds.
         */
        allocation?: string | null;
        id?: string | null;
      }[]
    | null;
  verification?: {
    status?: ('pending' | 'verified' | 'needs-review') | null;
    verifiedAt?: string | null;
    notes?: string | null;
  };
  reports?:
    | {
        title: string;
        period: string;
        externalUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Promote this entry in curated modules.
   */
  isFeatured?: boolean | null;
  seo?: {
    /**
     * Optional override for browser and search result titles.
     */
    metaTitle?: string | null;
    /**
     * Optional search description. Keep it concise.
     */
    metaDescription?: string | null;
    openGraphImage?: (number | null) | Media;
  };
  /**
   * The homepage reads the first published record marked current.
   */
  isCurrent?: boolean | null;
  isPublished?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-stats".
 */
export interface ImpactStat {
  id: number;
  label: string;
  value: number;
  metricType: 'projected' | 'committed' | 'transferred' | 'verified';
  prefix?: string | null;
  suffix?: string | null;
  detail: string;
  drop?: (number | null) | Drop;
  cause?: (number | null) | Cause;
  /**
   * Example: Batch 001 or Q3 2026.
   */
  period?: string | null;
  /**
   * Public source, report URL, or internal verification note.
   */
  source?: string | null;
  measuredAt?: string | null;
  /**
   * Promote this entry in curated modules.
   */
  isFeatured?: boolean | null;
  isPublished?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-entries".
 */
export interface ImpactEntry {
  id: number;
  title: string;
  description: string;
  /**
   * An additive allocation. Do not record the same funds again when their verification state changes.
   */
  amount: number;
  currency: 'USD';
  /**
   * The evidence state for this distinct allocation.
   */
  metricType: 'projected' | 'committed' | 'transferred' | 'verified';
  impactValue?: number | null;
  impactLabel?: string | null;
  impactSuffix?: string | null;
  occurredAt: string;
  cause: number | Cause;
  drop?: (number | null) | Drop;
  /**
   * Public report, transfer reference, or field update title.
   */
  source?: string | null;
  isPublished?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal".
 */
export interface Journal {
  id: number;
  /**
   * Lowercase letters, numbers, and hyphens only.
   */
  slug: string;
  title: string;
  category: 'studio' | 'drop-notes' | 'artist-story' | 'impact-report' | 'field-note';
  excerpt: string;
  image?: (number | null) | Media;
  /**
   * Optional fallback for migrated fixture images. Prefer local media uploads for production content.
   */
  externalImageUrl?: string | null;
  imageAlt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  authorName: string;
  publishedAt?: string | null;
  readTime?: number | null;
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  relatedDrop?: (number | null) | Drop;
  relatedArtist?: (number | null) | Artist;
  relatedCause?: (number | null) | Cause;
  /**
   * Promote this entry in curated modules.
   */
  isFeatured?: boolean | null;
  seo?: {
    /**
     * Optional override for browser and search result titles.
     */
    metaTitle?: string | null;
    /**
     * Optional search description. Keep it concise.
     */
    metaDescription?: string | null;
    openGraphImage?: (number | null) | Media;
  };
  isPublished?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  personName: string;
  relationship: 'collector' | 'artist' | 'ngo-partner' | 'press' | 'community-member';
  role?: string | null;
  avatar?: (number | null) | Media;
  rating?: number | null;
  /**
   * Optional source label, e.g. email, press article, or partner report.
   */
  source?: string | null;
  sourceUrl?: string | null;
  relatedDrop?: (number | null) | Drop;
  /**
   * Promote this entry in curated modules.
   */
  isFeatured?: boolean | null;
  isPublished?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category: 'orders' | 'products' | 'drops' | 'artists' | 'impact' | 'shipping-returns';
  audience?: ('collectors' | 'artists' | 'ngo-partners' | 'all') | null;
  isPublished?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-sections".
 */
export interface HomepageSection {
  id: number;
  section:
    | 'hero'
    | 'products'
    | 'drop'
    | 'design'
    | 'artist'
    | 'cause'
    | 'impact'
    | 'journal'
    | 'testimonials'
    | 'faq'
    | 'newsletter';
  layout: 'editorial' | 'immersive-image' | 'split-story' | 'metric-band' | 'product-rail' | 'question-list';
  title: string;
  eyebrow?: string | null;
  summary?: string | null;
  image?: (number | null) | Media;
  /**
   * Optional fallback for migrated fixture images. Prefer local media uploads for production content.
   */
  externalImageUrl?: string | null;
  imageAlt: string;
  signatureInteraction?:
    | ('image-reveal' | 'parallax-frame' | 'hotspots' | 'animated-counter' | 'horizontal-rail' | 'accordion' | 'none')
    | null;
  cta?: {
    label?: string | null;
    href?: string | null;
    style?: ('primary' | 'secondary' | 'text') | null;
  };
  featuredProducts?: (number | Product)[] | null;
  featuredDrop?: (number | null) | Drop;
  featuredArtist?: (number | null) | Artist;
  featuredArtwork?: (number | null) | Artwork;
  featuredCause?: (number | null) | Cause;
  featuredStats?: (number | ImpactStat)[] | null;
  supportingItems?:
    | {
        label: string;
        value?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The homepage reads the first published record marked current.
   */
  isCurrent?: boolean | null;
  isPublished?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter".
 */
export interface Newsletter {
  id: number;
  email: string;
  status: 'subscribed' | 'unsubscribed' | 'pending' | 'bounced';
  firstName?: string | null;
  source?: ('homepage' | 'product-page' | 'drop-page' | 'journal' | 'admin-import' | 'other') | null;
  interests?:
    | {
        topic: 'drops' | 'artists' | 'impact' | 'journal';
        id?: string | null;
      }[]
    | null;
  consent: {
    acceptedMarketing: boolean;
    acceptedAt?: string | null;
    ipAddress?: string | null;
  };
  /**
   * Private admin notes.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  customer?: (number | null) | User;
  email?: string | null;
  guestTokenHash: string;
  status: 'active' | 'converted' | 'abandoned' | 'expired';
  items?:
    | {
        product: number | Product;
        variantId: string;
        sku: string;
        productName: string;
        variantName: string;
        shippingProfile: 'standard' | 'fragile' | 'textile' | 'digital';
        quantity: number;
        /**
         * Stored in the currency's smallest unit (cents for USD/EUR/GBP).
         */
        unitPrice: number;
        /**
         * Stored in the currency's smallest unit (cents for USD/EUR/GBP).
         */
        lineTotal: number;
        currency: 'USD' | 'LBP' | 'EUR' | 'GBP';
        id?: string | null;
      }[]
    | null;
  coupon?: (number | null) | Coupon;
  couponCode?: string | null;
  shippingMethod?: (number | null) | ShippingMethod;
  shippingEstimate?: {
    country?: string | null;
    postalCode?: string | null;
    methodCode?: string | null;
    methodName?: string | null;
    minimumDeliveryDays?: number | null;
    maximumDeliveryDays?: number | null;
  };
  itemCount: number;
  /**
   * Stored in the currency's smallest unit (cents for USD/EUR/GBP).
   */
  subtotal: number;
  /**
   * Stored in the currency's smallest unit (cents for USD/EUR/GBP).
   */
  discountTotal: number;
  /**
   * Stored in the currency's smallest unit (cents for USD/EUR/GBP).
   */
  shippingTotal: number;
  /**
   * Stored in the currency's smallest unit (cents for USD/EUR/GBP).
   */
  taxTotal: number;
  /**
   * Stored in the currency's smallest unit (cents for USD/EUR/GBP).
   */
  total: number;
  currency: 'USD' | 'LBP' | 'EUR' | 'GBP';
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: number;
  code: string;
  discountType: 'percentage' | 'fixed' | 'free-shipping';
  /**
   * Percentage points, or a major-unit amount for fixed discounts.
   */
  value: number;
  currency?: ('USD' | 'LBP' | 'EUR' | 'GBP') | null;
  minimumSubtotal?: number | null;
  maximumDiscount?: number | null;
  maximumUses?: number | null;
  uses: number;
  startsAt?: string | null;
  endsAt?: string | null;
  applicableProducts?: (number | Product)[] | null;
  excludedProducts?: (number | Product)[] | null;
  isActive: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-methods".
 */
export interface ShippingMethod {
  id: number;
  code: string;
  name: string;
  description?: string | null;
  /**
   * Major-unit shipping price.
   */
  rate: number;
  /**
   * Optional major-unit subtotal threshold.
   */
  freeAbove?: number | null;
  currency: 'USD' | 'LBP' | 'EUR' | 'GBP';
  countries: {
    /**
     * ISO 3166-1 alpha-2 code, or ZZ as a worldwide fallback.
     */
    code: string;
    id?: string | null;
  }[];
  allowedProfiles?: ('standard' | 'fragile' | 'textile' | 'digital')[] | null;
  minimumDeliveryDays: number;
  maximumDeliveryDays: number;
  isActive: boolean;
  sortOrder: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  cart: number | Cart;
  customer?: (number | null) | User;
  customerEmail: string;
  guestTokenHash: string;
  status:
    'pending-payment' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'expired' | 'refunded';
  paymentStatus: 'not-started' | 'pending' | 'authorized' | 'paid' | 'failed' | 'partially-refunded' | 'refunded';
  inventoryStatus: 'reserved' | 'committed' | 'released';
  items: {
    product: number | Product;
    variantId: string;
    sku: string;
    productName: string;
    variantName: string;
    shippingProfile: 'standard' | 'fragile' | 'textile' | 'digital';
    quantity: number;
    /**
     * Stored in the currency's smallest unit (cents for USD/EUR/GBP).
     */
    unitPrice: number;
    /**
     * Stored in the currency's smallest unit (cents for USD/EUR/GBP).
     */
    lineTotal: number;
    currency: 'USD' | 'LBP' | 'EUR' | 'GBP';
    id?: string | null;
  }[];
  shippingAddress: {
    name: string;
    company?: string | null;
    line1: string;
    line2?: string | null;
    city: string;
    state?: string | null;
    postalCode?: string | null;
    /**
     * ISO 3166-1 alpha-2 country code.
     */
    country: string;
    phone: string;
  };
  billingAddress: {
    name: string;
    company?: string | null;
    line1: string;
    line2?: string | null;
    city: string;
    state?: string | null;
    postalCode?: string | null;
    /**
     * ISO 3166-1 alpha-2 country code.
     */
    country: string;
    phone: string;
  };
  coupon?: (number | null) | Coupon;
  couponCode?: string | null;
  shippingMethod: number | ShippingMethod;
  shippingMethodCode: string;
  shippingMethodName: string;
  itemCount: number;
  /**
   * Stored in the currency's smallest unit (cents for USD/EUR/GBP).
   */
  subtotal: number;
  /**
   * Stored in the currency's smallest unit (cents for USD/EUR/GBP).
   */
  discountTotal: number;
  /**
   * Stored in the currency's smallest unit (cents for USD/EUR/GBP).
   */
  shippingTotal: number;
  /**
   * Stored in the currency's smallest unit (cents for USD/EUR/GBP).
   */
  taxTotal: number;
  /**
   * Stored in the currency's smallest unit (cents for USD/EUR/GBP).
   */
  total: number;
  currency: 'USD' | 'LBP' | 'EUR' | 'GBP';
  reservationExpiresAt: string;
  paidAt?: string | null;
  cancelledAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  order: number | Order;
  provider: string;
  type: 'authorization' | 'capture' | 'sale' | 'refund' | 'void';
  status: 'pending' | 'succeeded' | 'failed' | 'cancelled';
  /**
   * Stored in the currency's smallest unit (cents for USD/EUR/GBP).
   */
  amount: number;
  currency: 'USD' | 'LBP' | 'EUR' | 'GBP';
  idempotencyKey: string;
  externalId?: string | null;
  /**
   * Non-secret provider references and status metadata only.
   */
  providerData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  failureCode?: string | null;
  failureMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory-movements".
 */
export interface InventoryMovement {
  id: number;
  product: number | Product;
  variantId: string;
  sku: string;
  cart?: (number | null) | Cart;
  order?: (number | null) | Order;
  movementType: 'reserve' | 'release' | 'sale' | 'restock' | 'adjustment';
  quantity: number;
  inventoryAfter: number;
  reservedAfter: number;
  idempotencyKey: string;
  reason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  topic: string;
  orderNumber?: string | null;
  message: string;
  status: 'new' | 'in-progress' | 'resolved' | 'spam';
  consentToReply: boolean;
  requestFingerprint?: string | null;
  resolvedAt?: string | null;
  /**
   * Private staff notes.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'drops';
        value: number | Drop;
      } | null)
    | ({
        relationTo: 'artworks';
        value: number | Artwork;
      } | null)
    | ({
        relationTo: 'artists';
        value: number | Artist;
      } | null)
    | ({
        relationTo: 'causes';
        value: number | Cause;
      } | null)
    | ({
        relationTo: 'impact-stats';
        value: number | ImpactStat;
      } | null)
    | ({
        relationTo: 'impact-entries';
        value: number | ImpactEntry;
      } | null)
    | ({
        relationTo: 'journal';
        value: number | Journal;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'homepage-sections';
        value: number | HomepageSection;
      } | null)
    | ({
        relationTo: 'newsletter';
        value: number | Newsletter;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'coupons';
        value: number | Coupon;
      } | null)
    | ({
        relationTo: 'shipping-methods';
        value: number | ShippingMethod;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null)
    | ({
        relationTo: 'inventory-movements';
        value: number | InventoryMovement;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  name?: T;
  wishlist?: T;
  addresses?:
    | T
    | {
        label?: T;
        isDefault?: T;
        name?: T;
        company?: T;
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  usage?: T;
  focalPoint?:
    | T
    | {
        x?: T;
        y?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  form?: T;
  price?: T;
  currency?: T;
  minPrice?: T;
  maxPrice?: T;
  edition?: T;
  image?: T;
  externalImageUrl?: T;
  imageAlt?: T;
  gallery?:
    | T
    | {
        image?: T;
        externalImageUrl?: T;
        alt?: T;
        id?: T;
      };
  story?: T;
  dimensions?: T;
  careInstructions?: T;
  shippingReturns?: T;
  drop?: T;
  artist?: T;
  artwork?: T;
  cause?: T;
  materials?:
    | T
    | {
        label?: T;
        id?: T;
      };
  variants?:
    | T
    | {
        name?: T;
        sku?: T;
        price?: T;
        compareAtPrice?: T;
        color?: T;
        size?: T;
        inventory?: T;
        reserved?: T;
        lowStockThreshold?: T;
        attributes?:
          | T
          | {
              name?: T;
              value?: T;
              id?: T;
            };
        isAvailable?: T;
        id?: T;
      };
  colors?: T;
  sizes?: T;
  availability?: T;
  searchKeywords?: T;
  totalInventory?: T;
  shippingProfile?: T;
  upsells?: T;
  isFeatured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        openGraphImage?: T;
      };
  isPublished?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "drops_select".
 */
export interface DropsSelect<T extends boolean = true> {
  slug?: T;
  eyebrow?: T;
  title?: T;
  summary?: T;
  batchSize?: T;
  reserved?: T;
  status?: T;
  opensAt?: T;
  closesAt?: T;
  products?: T;
  artist?: T;
  artwork?: T;
  cause?: T;
  donationPercentage?: T;
  image?: T;
  externalImageUrl?: T;
  imageAlt?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  milestones?:
    | T
    | {
        label?: T;
        value?: T;
        progress?: T;
        id?: T;
      };
  allocation?:
    | T
    | {
        label?: T;
        percentage?: T;
        description?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
        style?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        openGraphImage?: T;
      };
  isCurrent?: T;
  isPublished?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artworks_select".
 */
export interface ArtworksSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  artistLine?: T;
  summary?: T;
  image?: T;
  externalImageUrl?: T;
  imageAlt?: T;
  details?:
    | T
    | {
        label?: T;
        title?: T;
        body?: T;
        x?: T;
        y?: T;
        id?: T;
      };
  isCurrent?: T;
  isPublished?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artists_select".
 */
export interface ArtistsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  role?: T;
  quote?: T;
  bio?: T;
  location?: T;
  website?: T;
  instagram?: T;
  image?: T;
  externalImageUrl?: T;
  imageAlt?: T;
  processVideo?: T;
  processVideoUrl?: T;
  processVideoPoster?: T;
  processVideoCaption?: T;
  portraitGallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  facts?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  representativeWorks?:
    | T
    | {
        title?: T;
        year?: T;
        medium?: T;
        image?: T;
        id?: T;
      };
  isFeatured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        openGraphImage?: T;
      };
  isCurrent?: T;
  isPublished?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "causes_select".
 */
export interface CausesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  focus?: T;
  legalName?: T;
  registrationNumber?: T;
  website?: T;
  summary?: T;
  contact?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
      };
  image?: T;
  externalImageUrl?: T;
  imageAlt?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  metrics?:
    | T
    | {
        label?: T;
        value?: T;
        progress?: T;
        id?: T;
      };
  programs?:
    | T
    | {
        name?: T;
        description?: T;
        allocation?: T;
        id?: T;
      };
  verification?:
    | T
    | {
        status?: T;
        verifiedAt?: T;
        notes?: T;
      };
  reports?:
    | T
    | {
        title?: T;
        period?: T;
        externalUrl?: T;
        id?: T;
      };
  isFeatured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        openGraphImage?: T;
      };
  isCurrent?: T;
  isPublished?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-stats_select".
 */
export interface ImpactStatsSelect<T extends boolean = true> {
  label?: T;
  value?: T;
  metricType?: T;
  prefix?: T;
  suffix?: T;
  detail?: T;
  drop?: T;
  cause?: T;
  period?: T;
  source?: T;
  measuredAt?: T;
  isFeatured?: T;
  isPublished?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-entries_select".
 */
export interface ImpactEntriesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  amount?: T;
  currency?: T;
  metricType?: T;
  impactValue?: T;
  impactLabel?: T;
  impactSuffix?: T;
  occurredAt?: T;
  cause?: T;
  drop?: T;
  source?: T;
  isPublished?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal_select".
 */
export interface JournalSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  category?: T;
  excerpt?: T;
  image?: T;
  externalImageUrl?: T;
  imageAlt?: T;
  content?: T;
  authorName?: T;
  publishedAt?: T;
  readTime?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  relatedDrop?: T;
  relatedArtist?: T;
  relatedCause?: T;
  isFeatured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        openGraphImage?: T;
      };
  isPublished?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  personName?: T;
  relationship?: T;
  role?: T;
  avatar?: T;
  rating?: T;
  source?: T;
  sourceUrl?: T;
  relatedDrop?: T;
  isFeatured?: T;
  isPublished?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  audience?: T;
  isPublished?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-sections_select".
 */
export interface HomepageSectionsSelect<T extends boolean = true> {
  section?: T;
  layout?: T;
  title?: T;
  eyebrow?: T;
  summary?: T;
  image?: T;
  externalImageUrl?: T;
  imageAlt?: T;
  signatureInteraction?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
        style?: T;
      };
  featuredProducts?: T;
  featuredDrop?: T;
  featuredArtist?: T;
  featuredArtwork?: T;
  featuredCause?: T;
  featuredStats?: T;
  supportingItems?:
    | T
    | {
        label?: T;
        value?: T;
        description?: T;
        id?: T;
      };
  isCurrent?: T;
  isPublished?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter_select".
 */
export interface NewsletterSelect<T extends boolean = true> {
  email?: T;
  status?: T;
  firstName?: T;
  source?: T;
  interests?:
    | T
    | {
        topic?: T;
        id?: T;
      };
  consent?:
    | T
    | {
        acceptedMarketing?: T;
        acceptedAt?: T;
        ipAddress?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  customer?: T;
  email?: T;
  guestTokenHash?: T;
  status?: T;
  items?:
    | T
    | {
        product?: T;
        variantId?: T;
        sku?: T;
        productName?: T;
        variantName?: T;
        shippingProfile?: T;
        quantity?: T;
        unitPrice?: T;
        lineTotal?: T;
        currency?: T;
        id?: T;
      };
  coupon?: T;
  couponCode?: T;
  shippingMethod?: T;
  shippingEstimate?:
    | T
    | {
        country?: T;
        postalCode?: T;
        methodCode?: T;
        methodName?: T;
        minimumDeliveryDays?: T;
        maximumDeliveryDays?: T;
      };
  itemCount?: T;
  subtotal?: T;
  discountTotal?: T;
  shippingTotal?: T;
  taxTotal?: T;
  total?: T;
  currency?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  cart?: T;
  customer?: T;
  customerEmail?: T;
  guestTokenHash?: T;
  status?: T;
  paymentStatus?: T;
  inventoryStatus?: T;
  items?:
    | T
    | {
        product?: T;
        variantId?: T;
        sku?: T;
        productName?: T;
        variantName?: T;
        shippingProfile?: T;
        quantity?: T;
        unitPrice?: T;
        lineTotal?: T;
        currency?: T;
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        name?: T;
        company?: T;
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  billingAddress?:
    | T
    | {
        name?: T;
        company?: T;
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  coupon?: T;
  couponCode?: T;
  shippingMethod?: T;
  shippingMethodCode?: T;
  shippingMethodName?: T;
  itemCount?: T;
  subtotal?: T;
  discountTotal?: T;
  shippingTotal?: T;
  taxTotal?: T;
  total?: T;
  currency?: T;
  reservationExpiresAt?: T;
  paidAt?: T;
  cancelledAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  code?: T;
  discountType?: T;
  value?: T;
  currency?: T;
  minimumSubtotal?: T;
  maximumDiscount?: T;
  maximumUses?: T;
  uses?: T;
  startsAt?: T;
  endsAt?: T;
  applicableProducts?: T;
  excludedProducts?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-methods_select".
 */
export interface ShippingMethodsSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  description?: T;
  rate?: T;
  freeAbove?: T;
  currency?: T;
  countries?:
    | T
    | {
        code?: T;
        id?: T;
      };
  allowedProfiles?: T;
  minimumDeliveryDays?: T;
  maximumDeliveryDays?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  order?: T;
  provider?: T;
  type?: T;
  status?: T;
  amount?: T;
  currency?: T;
  idempotencyKey?: T;
  externalId?: T;
  providerData?: T;
  failureCode?: T;
  failureMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory-movements_select".
 */
export interface InventoryMovementsSelect<T extends boolean = true> {
  product?: T;
  variantId?: T;
  sku?: T;
  cart?: T;
  order?: T;
  movementType?: T;
  quantity?: T;
  inventoryAfter?: T;
  reservedAfter?: T;
  idempotencyKey?: T;
  reason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  topic?: T;
  orderNumber?: T;
  message?: T;
  status?: T;
  consentToReply?: T;
  requestFingerprint?: T;
  resolvedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The public brand story, mission, values, and founder narrative.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  hero: {
    eyebrow: string;
    title: string;
    introduction: string;
    image?: (number | null) | Media;
    /**
     * Optional fallback for migrated fixture images. Prefer local media uploads for production content.
     */
    externalImageUrl?: string | null;
    imageAlt: string;
  };
  story: {
    heading: string;
    body: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    image?: (number | null) | Media;
    /**
     * Optional fallback for migrated fixture images. Prefer local media uploads for production content.
     */
    externalImageUrl?: string | null;
    imageAlt: string;
  };
  mission: {
    eyebrow?: string | null;
    heading: string;
    body: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    cta?: {
      label?: string | null;
      href?: string | null;
      style?: ('primary' | 'secondary' | 'text') | null;
    };
  };
  values: {
    title: string;
    description: string;
    id?: string | null;
  }[];
  founder: {
    name: string;
    role: string;
    quote?: string | null;
    story: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    image?: (number | null) | Media;
    /**
     * Optional fallback for migrated fixture images. Prefer local media uploads for production content.
     */
    externalImageUrl?: string | null;
    imageAlt: string;
  };
  milestones?:
    | {
        year: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Optional override for browser and search result titles.
     */
    metaTitle?: string | null;
    /**
     * Optional search description. Keep it concise.
     */
    metaDescription?: string | null;
    openGraphImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Contact page copy, public details, and enquiry routing options.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  eyebrow: string;
  title: string;
  introduction: string;
  details: {
    email: string;
    phone?: string | null;
    address?: string | null;
    hours?: string | null;
  };
  topics?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown beside the enquiry form.
   */
  responseNote?: string | null;
  seo?: {
    /**
     * Optional override for browser and search result titles.
     */
    metaTitle?: string | null;
    /**
     * Optional search description. Keep it concise.
     */
    metaDescription?: string | null;
    openGraphImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        introduction?: T;
        image?: T;
        externalImageUrl?: T;
        imageAlt?: T;
      };
  story?:
    | T
    | {
        heading?: T;
        body?: T;
        image?: T;
        externalImageUrl?: T;
        imageAlt?: T;
      };
  mission?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
              style?: T;
            };
      };
  values?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  founder?:
    | T
    | {
        name?: T;
        role?: T;
        quote?: T;
        story?: T;
        image?: T;
        externalImageUrl?: T;
        imageAlt?: T;
      };
  milestones?:
    | T
    | {
        year?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        openGraphImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  introduction?: T;
  details?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
        hours?: T;
      };
  topics?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  responseNote?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        openGraphImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}