"use client";

import { motion, useReducedMotion } from "framer-motion";
import { ArrowRight, ArrowUpRight, BadgeCheck, ExternalLink, FileText, Mail, Phone } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";

import { Button } from "@/components/ui/button";
import { MOTION_EASE, sectionReveal } from "@/lib/motion";
import { cn } from "@/lib/utils";
import type { CauseDrop, CauseProfile as CauseProfileData } from "@/types/cause";

type CauseProfileProps = { cause: CauseProfileData };

export function CauseProfile({ cause }: CauseProfileProps) {
  const reducedMotion = useReducedMotion();
  const [selectedDrop, setSelectedDrop] = useState(0);
  const reveal = reducedMotion ? { initial: false as const } : sectionReveal;
  const selected = cause.drops[selectedDrop];

  return <main id="main-content" className="min-h-screen bg-[var(--ae-parchment)] pt-16">
    <section className="bg-[var(--ae-forest)] text-[var(--ae-white)]"><div className="ae-container grid min-h-[min(48rem,calc(100svh-4rem))] gap-0 lg:grid-cols-[.8fr_1.2fr]">
      <motion.div initial={reducedMotion ? false : { opacity: 0, x: -18 }} animate={reducedMotion ? undefined : { opacity: 1, x: 0 }} transition={{ duration: 0.75, ease: [0.22, 1, 0.36, 1] }} className="relative min-h-[28rem] overflow-hidden bg-[var(--ae-forest-soft)] lg:min-h-0">
        {cause.image ? <Image src={cause.image.src} alt={cause.image.alt} fill priority sizes="(max-width: 1023px) 100vw, 42vw" className="object-cover" /> : null}<div aria-hidden="true" className="absolute inset-0 bg-[linear-gradient(0deg,rgba(0,0,0,.46),transparent_45%)]" />
      </motion.div>
      <div className="flex flex-col justify-end py-12 sm:py-16 lg:px-[clamp(2.5rem,7vw,7rem)]"><motion.div initial={reducedMotion ? false : { opacity: 0, y: 22 }} animate={reducedMotion ? undefined : { opacity: 1, y: 0 }} transition={{ delay: 0.12, duration: 0.72, ease: [0.22, 1, 0.36, 1] }}><p className="ae-kicker">NGO partner</p><h1 className="ae-display mt-5 text-[clamp(5rem,11vw,8.8rem)] font-light leading-[.72] tracking-[-.05em]">{cause.name}</h1><p className="mt-6 text-xs font-medium uppercase tracking-[.14em] text-white/55">{cause.focus}</p><p className="mt-8 max-w-2xl text-base leading-7 text-white/75 sm:text-lg sm:leading-8">{cause.summary}</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg" className="bg-[var(--ae-white)] text-[var(--ae-forest)] hover:bg-[var(--ae-fog)]"><a href="#mission">Our mission <ArrowRight className="size-4" aria-hidden="true" /></a></Button>{cause.drops[0] ? <Button asChild size="lg" variant="outline" className="border-white/30 text-white hover:border-[var(--ae-gilt)] hover:bg-transparent hover:text-[var(--ae-gilt)]"><Link href={`/drops/${cause.drops[0].slug}`}>View supporting drops <ArrowUpRight className="size-4" aria-hidden="true" /></Link></Button> : null}</div></motion.div></div>
    </div></section>

    <section id="mission" className="ae-section scroll-mt-16"><motion.div {...reveal} className="ae-container grid gap-12 lg:grid-cols-[.88fr_1.12fr] lg:gap-24"><div><p className="ae-kicker">Mission</p><h2 className="ae-display mt-4 text-5xl font-light leading-[.86] text-[var(--ae-forest)] sm:text-6xl">Care is a practice that continues.</h2></div><div><p className="max-w-2xl text-lg leading-8 text-[var(--muted-foreground)]">{cause.summary}</p><dl className="mt-10 divide-y divide-[var(--border)] border-y border-[var(--border)]">{cause.legalName ? <InfoRow label="Legal name" value={cause.legalName} /> : null}{cause.registrationNumber ? <InfoRow label="Registration" value={cause.registrationNumber} /> : null}{cause.verificationStatus === "verified" ? <InfoRow label="Partner status" value={<span className="inline-flex items-center gap-2"><BadgeCheck className="size-4 text-[var(--ae-gilt)]" aria-hidden="true" />Verified</span>} /> : null}</dl><div className="mt-7 flex flex-wrap gap-x-6 gap-y-3">{cause.website ? <a href={cause.website} target="_blank" rel="noreferrer" className="focus-ring inline-flex items-center gap-2 border-b border-[var(--ae-gilt)] pb-1 text-sm font-medium text-[var(--ae-forest)] transition hover:text-[var(--ae-gilt)]"><ExternalLink className="size-4" aria-hidden="true" />Website</a> : null}{cause.contact?.email ? <a href={`mailto:${cause.contact.email}`} className="focus-ring inline-flex items-center gap-2 border-b border-[var(--ae-gilt)] pb-1 text-sm font-medium text-[var(--ae-forest)] transition hover:text-[var(--ae-gilt)]"><Mail className="size-4" aria-hidden="true" />Contact</a> : null}{cause.contact?.phone ? <a href={`tel:${cause.contact.phone.replace(/[^+\d]/g, "")}`} className="focus-ring inline-flex items-center gap-2 border-b border-[var(--ae-gilt)] pb-1 text-sm font-medium text-[var(--ae-forest)] transition hover:text-[var(--ae-gilt)]"><Phone className="size-4" aria-hidden="true" />Call</a> : null}</div></div></motion.div></section>

    {cause.programs.length ? <section aria-labelledby="programs-title" className="bg-[var(--ae-fog)] py-[var(--ae-space-section)]"><motion.div {...reveal} className="ae-container"><div className="max-w-2xl"><p className="ae-kicker">Projects in focus</p><h2 id="programs-title" className="ae-display mt-4 text-5xl font-light leading-[.86] text-[var(--ae-forest)] sm:text-6xl">The work your collection supports.</h2></div><div className="mt-10 grid gap-px overflow-hidden border border-[var(--border)] bg-[var(--border)] md:grid-cols-2">{cause.programs.map((program, index) => <article key={program.name} className="bg-[var(--ae-white)] p-6 sm:p-8"><span className="ae-display text-4xl text-[var(--ae-gilt)]">{String(index + 1).padStart(2, "0")}</span><h3 className="ae-display mt-8 text-4xl font-medium leading-none text-[var(--ae-forest)]">{program.name}</h3><p className="mt-4 max-w-lg text-sm leading-7 text-[var(--muted-foreground)]">{program.description}</p>{program.allocation ? <p className="mt-7 border-t border-[var(--border)] pt-4 text-xs font-medium uppercase tracking-[.12em] text-[var(--ae-stone)]">{program.allocation}</p> : null}</article>)}</div></motion.div></section> : null}

    {cause.drops.length ? <section aria-labelledby="supported-drops-title" className="ae-section"><motion.div {...reveal} className="ae-container"><div className="grid gap-8 lg:grid-cols-[.75fr_1.25fr] lg:items-end"><div><p className="ae-kicker">Supported by ArtEffect</p><h2 id="supported-drops-title" className="ae-display mt-4 text-5xl font-light leading-[.86] text-[var(--ae-forest)] sm:text-6xl">A direct share of every drop.</h2><p className="mt-6 max-w-sm text-sm leading-7 text-[var(--muted-foreground)]">The donation percentage is set before a batch launches, then carried into its public impact reporting.</p></div><div className="divide-y divide-[var(--border)] border-y border-[var(--border)]">{cause.drops.map((drop, index) => <button key={drop.slug} type="button" onClick={() => setSelectedDrop(index)} className="focus-ring group grid w-full grid-cols-[2.5rem_1fr_auto] items-center gap-3 py-5 text-left" aria-pressed={selectedDrop === index}><span className={cn("ae-display text-2xl", selectedDrop === index ? "text-[var(--ae-gilt)]" : "text-[var(--ae-stone)]")}>{String(index + 1).padStart(2, "0")}</span><span><span className="block text-base font-medium text-[var(--ae-forest)]">{drop.title}</span><span className="mt-1 block text-xs uppercase tracking-[.1em] text-[var(--ae-stone)]">{drop.eyebrow}</span></span><span className="text-right"><span className="ae-display block text-3xl text-[var(--ae-gilt)]">{drop.donationPercentage ?? "—"}{drop.donationPercentage !== undefined ? "%" : ""}</span><span className="text-[.65rem] uppercase tracking-[.1em] text-[var(--ae-stone)]">to the NGO</span></span></button>)}</div></div>{selected ? <SupportedDropCard drop={selected} /> : null}</motion.div></section> : null}

    {cause.metrics.length ? <section aria-labelledby="progress-title" className="bg-[var(--ae-forest)] py-[var(--ae-space-section)] text-[var(--ae-white)]"><motion.div {...reveal} className="ae-container grid gap-10 lg:grid-cols-[.72fr_1.28fr] lg:items-end"><div><p className="ae-kicker">Progress ledger</p><h2 id="progress-title" className="ae-display mt-4 text-5xl font-light leading-[.86] sm:text-6xl">Measured over time.</h2><p className="mt-6 max-w-sm text-sm leading-7 text-white/65">A useful impact number needs its context. These markers show the work currently being funded and followed.</p></div><div className="grid gap-7">{cause.metrics.map((metric) => <ProgressMetric key={metric.label} {...metric} reducedMotion={reducedMotion} />)}</div></motion.div></section> : null}

    {cause.gallery.length ? <section aria-labelledby="field-notes-title" className="ae-section"><motion.div {...reveal} className="ae-container"><div className="max-w-xl"><p className="ae-kicker">Field notes</p><h2 id="field-notes-title" className="ae-display mt-4 text-5xl font-light leading-[.86] text-[var(--ae-forest)] sm:text-6xl">The landscape behind the ledger.</h2></div><div className="mt-10 grid gap-5 md:grid-cols-12">{cause.gallery.map((image, index) => <figure key={`${image.src}-${index}`} className={cn(index === 0 ? "md:col-span-7" : index === 1 ? "md:col-span-5" : "md:col-span-6")}><div className={cn("relative overflow-hidden bg-[var(--ae-fog)]", index === 0 ? "aspect-[4/3]" : "aspect-[3/4]")}><Image src={image.src} alt={image.alt} fill sizes={index === 0 ? "(max-width: 767px) 100vw, 58vw" : "(max-width: 767px) 100vw, 42vw"} className="object-cover" /></div>{image.caption ? <figcaption className="mt-3 text-sm leading-6 text-[var(--muted-foreground)]">{image.caption}</figcaption> : null}</figure>)}</div></motion.div></section> : null}

    {cause.products.length ? <section aria-labelledby="editions-title" className="bg-[var(--ae-onyx)] py-[var(--ae-space-section)] text-[var(--ae-white)]"><motion.div {...reveal} className="ae-container"><p className="ae-kicker">Collect to support</p><h2 id="editions-title" className="ae-display mt-4 text-5xl font-light leading-[.86] sm:text-6xl">Editions with a route to the field.</h2><div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{cause.products.map((product) => <Link key={product.slug} href={`/shop/${product.slug}`} className="focus-ring group"><div className="relative aspect-[4/5] overflow-hidden bg-[var(--ae-forest-soft)]"><Image src={product.image} alt={product.imageAlt} fill sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw" className="object-cover transition duration-700 group-hover:scale-[1.025]" /></div><div className="mt-4 flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.12em] text-white/45">{product.form}</p><h3 className="ae-display mt-1 text-3xl font-medium leading-none">{product.name}</h3></div><span className="text-sm text-[var(--ae-gilt)]">{product.displayPrice}</span></div></Link>)}</div></motion.div></section> : null}

    {cause.reports.length ? <section aria-labelledby="reports-title" className="border-t border-[var(--border)] bg-[var(--ae-white)]"><div className="ae-container py-12"><p className="ae-kicker">Reporting</p><h2 id="reports-title" className="ae-display mt-3 text-4xl font-light text-[var(--ae-forest)]">Read the updates.</h2><div className="mt-7 grid gap-px border border-[var(--border)] bg-[var(--border)] md:grid-cols-2">{cause.reports.map((report) => report.externalUrl ? <a key={`${report.title}-${report.period}`} href={report.externalUrl} target="_blank" rel="noreferrer" className="focus-ring flex items-center justify-between gap-4 bg-[var(--ae-parchment)] p-5 transition hover:bg-[var(--ae-fog)]"><span><span className="block font-medium text-[var(--ae-forest)]">{report.title}</span><span className="mt-1 block text-xs uppercase tracking-[.1em] text-[var(--ae-stone)]">{report.period}</span></span><ExternalLink className="size-4 text-[var(--ae-gilt)]" aria-hidden="true" /></a> : <div key={`${report.title}-${report.period}`} className="flex items-center gap-3 bg-[var(--ae-parchment)] p-5"><FileText className="size-4 text-[var(--ae-gilt)]" aria-hidden="true" /><span><span className="block font-medium text-[var(--ae-forest)]">{report.title}</span><span className="mt-1 block text-xs uppercase tracking-[.1em] text-[var(--ae-stone)]">{report.period}</span></span></div>)}</div></div></section> : null}
  </main>;
}

function InfoRow({ label, value }: { label: string; value: React.ReactNode }) { return <div className="grid grid-cols-[7rem_1fr] gap-4 py-4"><dt className="text-xs uppercase tracking-[.12em] text-[var(--ae-stone)]">{label}</dt><dd className="text-sm text-[var(--ae-forest)]">{value}</dd></div>; }
function SupportedDropCard({ drop }: { drop: CauseDrop }) { return <div className="mt-10 grid overflow-hidden border border-[var(--border)] bg-[var(--ae-white)] md:grid-cols-2">{drop.image ? <div className="relative aspect-[4/3] bg-[var(--ae-fog)] md:aspect-auto"><Image src={drop.image.src} alt={drop.image.alt} fill sizes="(max-width: 767px) 100vw, 50vw" className="object-cover" /></div> : null}<div className="flex flex-col justify-between p-6 sm:p-8"><div><p className="ae-kicker">{drop.eyebrow}</p><h3 className="ae-display mt-3 text-4xl font-medium leading-none text-[var(--ae-forest)]">{drop.title}</h3><p className="mt-5 text-sm leading-7 text-[var(--muted-foreground)]">{drop.summary}</p></div><div className="mt-8 flex items-end justify-between gap-4 border-t border-[var(--border)] pt-5"><p className="text-xs uppercase tracking-[.12em] text-[var(--ae-stone)]">NGO allocation</p><p className="ae-display text-5xl leading-none text-[var(--ae-gilt)]">{drop.donationPercentage ?? "—"}{drop.donationPercentage !== undefined ? "%" : ""}</p></div><Link href={`/drops/${drop.slug}`} className="focus-ring mt-7 inline-flex items-center gap-2 text-sm font-medium text-[var(--ae-forest)]">Explore the drop <ArrowUpRight className="size-4 text-[var(--ae-gilt)]" aria-hidden="true" /></Link></div></div>; }
function ProgressMetric({ label, progress, value, reducedMotion }: { label: string; progress: number; value: string; reducedMotion: boolean | null }) { return <div><div className="flex flex-wrap justify-between gap-x-5 gap-y-1 text-sm"><span className="font-medium text-white">{label}</span><span className="text-white/55">{value}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/15"><motion.div initial={reducedMotion ? false : { width: 0 }} whileInView={reducedMotion ? undefined : { width: `${progress}%` }} viewport={{ once: true }} transition={{ duration: 0.9, ease: MOTION_EASE }} className="h-full rounded-full bg-[var(--ae-gilt)]" style={reducedMotion ? { width: `${progress}%` } : undefined} /></div></div>; }
